version: "3"

services:
  weblb:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./www:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
    depends_on:
      - fephpfpm

  fephpfpm:
    image: achandre/php-demo:1.0.0
    deploy:
      replica: 2
    volumes:
      - ./www:/srv/www
    networks:
      - www
    env_file: .env
    depends_on:
      - mysql

  mysql:
    image: percona:ps-8
    ports:
      - 33061:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - www
    env_file: .env

volumes:
  dbdata:

networks:
  www:
